# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a70045848d4f65dca919ede7a6b69bf"
name = "lens"
handle = "lens-2"
application_url = "https://volt-begin-gnome-prospective.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://volt-begin-gnome-prospective.trycloudflare.com/auth/callback",
  "https://volt-begin-gnome-prospective.trycloudflare.com/auth/shopify/callback",
  "https://volt-begin-gnome-prospective.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
