# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f3208386385780dca87bbed9b95a030"
name = "lens"
handle = "lens-1"
application_url = "https://velocity-fee-butler-get.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://velocity-fee-butler-get.trycloudflare.com/auth/callback",
  "https://velocity-fee-butler-get.trycloudflare.com/auth/shopify/callback",
  "https://velocity-fee-butler-get.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
